(ns velho-ds.tokens.spacing)

(def space-x-large-rem "4rem")
(def space-xx-large "128px")
(def space-large "48px")
(def space-base "24px")
(def space-x-small-rem "0.5rem")
(def space-xx-large-rem "8rem")
(def space-base-rem "1.5rem")
(def space-large-rem "3rem")
(def space-small-rem "1rem")
(def space-x-small "8px")
(def space-xx-small-rem "0.25rem")
(def space-xx-small "4px")
(def space-x-large "64px")
(def space-small "16px")
